### PR TITLE
Feature/now

### PR DESCRIPTION
**Pull request by s1hofmann**
This PR enables snapshot releases for branches.

Every branch and PR is deployed via zeit Now and publicly available.
Local builds are not necessarily required anymore.

### CODE REVIEW

**Comment by s1hofmann** [comment]
> In addition, current PRs just redirect to a file system which seems to be a clone of the source repo

The default behaviour for Zeit Now deployments is to publish the current repo content. Without the build config contained in this PR, our site is not being generated, which results in the directory listing.

Generated page content is available [on master](https://sakuligithubio-git-master.s1hofmann.now.sh/), so this deployment already shows valid content without build config.

**Comment by svettwer** [comment]
:bulb: :+1: 
Thx for the explaination.

**Comment by ZNicoZ** [comment]
Not sure about this but, if the site goes public with now on Zeit, please add a robot txt or something to prevent the site being crawled.

**Comment by svettwer** [comment]
Oh, you are right! That looked different as I reviewed the changes.

**Comment by s1hofmann** [comment]
We decided to switch from zeit nows GitHub integration to Travis + now cli deployment due to invalid build config

**Pull request merged**
